### ISSUE TITLE
Make changes to templates

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/article_templates#20]
This is a to-do list spinning off of discussion in #16 ; it will be updated as we get more discussion there. Currently, I'm expecting we'll want to make at least these changes to the template:

**Important:**
- [x] Setup checklists (perhaps a custom checklist environment) providing [visually appealing checklist-like panels](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-327872610)
- [x] Date, ~DOI and version~ in the left column of the first page (see #10 )
- [x] Add an official location for a link to the GitHub repo (below corresponding authors) have [a note steering reader comments/feedback to GitHub repo](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-330896332); also do the same in a subsection at the end just before author contributions, to emphasize the importance of this.
- [x] [Broaden conflicts section](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-330665758) to indicate how conflicts can be other than financial.
- [x] [Get rid of gutter after first page](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-331018737), [probably going to two column for subsequent pages](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-331718195)
- [x] Provide a way to easily display nicely formatted fixed-width code blocks for programming code/pseudocode, rather like what GitHub provides as discussed [here](https://github.com/livecomsjournal/livecomsjournal.github.io/issues/29#issuecomment-332718686), kind of like:
```python
x = 23
y = 37
for i in range(23): print x*y
```

**Probably nice to have:**
- [x] Sans serif math fonts to go with the sans serif text

**Very minor**
- [x] [p6 of our sample PDF has differing spacing between the lines](https://github.com/livecomsjournal/article_templates/blob/master/templates/livecoms-template-bestpractices.pdf) which seems odd and should probably be fixed.

**And in a final stage:**
- [x] After all of the above are done, create templates for the other article types (as in #9 ) 
- [x] Make custom changes for specific types of documents -- perhaps Best Practices documents should use [more of the full width of the page](https://github.com/livecomsjournal/article_templates/issues/16#issue-255951019) for body text and checklists
- [x] Organize each template as appropriate for the type of document; e.g. best practices documents may need to explicitly note scope, etc., as [noted here](https://github.com/livecomsjournal/article_templates/issues/16#issue-255951019).

**Comment by justinGilmer** [comment]
In reference to the checklist options, there seems to be a pretty decent option through the TeX package `enumitem`.
[Link here.](https://tex.stackexchange.com/a/313337)

It might need a tad more work, but it allows grouping, sublists, etc.

**Comment by davidlmobley** [comment]
That seems like it could work, though I also like the additional bells and whistles (visually appealing table/colorized look) provided by some of the checklists linked above, so I'd probably want to polish this somehow (which I don't know how to do).

**Comment by hmayes** [comment]
Another minor comment: I just these details in the references: the first author is in bold and there are no periods after initials. I prefer to keep those periods, but can live with this. I move dislike bolding the first name. What if there are "co-first authors"?

I also suggest adding "\usepackage{natmove}" to the template (moves the superscript references after punctuation), so we don't have to deal with inconsistencies between "\cite" added before or after commas and periods.

**Comment by mrshirts** [comment]
I've added natmove in PR https://github.com/livecomsjournal/article_templates/pull/21.

**Comment by davidlmobley** [comment]
Many of these were dealt with in #23 ; those that remain are for me to tackle.

**Comment by davidlmobley** [comment]
The last of these would be resolved by #41.
